// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jabqsfgbfnkxbimbgkma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphYnFzZmdiZm5reGJpbWJna21hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1OTMzNjgsImV4cCI6MjA2NzE2OTM2OH0.dVIi86zmaHF2AltBZuPR1zhncO8nL7-JRaj95X2_RUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});