// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://miyemekgyntxulzjghjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1peWVtZWtneW50eHVsempnaGp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTEyOTUsImV4cCI6MjA2MzkyNzI5NX0.ykyauVfxOZHiU6x9ciufm0ZXW7UKXd8UHeiIKvCXtU8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);